### ISSUE TITLE
ToDo Before End of Month

### ISSUE THREAD

**Issue by vsoch** [converged-computing/performance-study#7]
- [x] Debug size 256 cluster on AWS EKS - likely cni issue (fixed)
- [x] Need to check / validate each result output directory  - that we have all the results!
- [x] If time - run nekrs on Google Compute engine (we didn't do this, nor did we run it anywhere really)

cc @milroy
